In [ ]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

Above we are creating a tensor, x. Tensors are nothing but multi dimensional arrays. The example below is a 2 dimensional tensor.
The `.constant` function helps us create a constant tensor from a tensor-like object.

Tensors are multi-dimensional arrays with a uniform type (called a dtype). You can see all supported dtypes at tf.dtypes.DType.

If you're familiar with NumPy, tensors are (kind of) like np.arrays.

All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.

In [8]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])

print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


The important attributes of a tensor are it's `shape` and `dtype`
- `tensor.shape` tells us size of the tensor in terms of axes and elements within those axes
- `tensor.dtype` tells you the type of all the elements in the tensor
Tensorflow has standard operations for ML.
example...

In [9]:
x + x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [10]:
5 * x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5., 10., 15.],
       [20., 25., 30.]], dtype=float32)>

All of the operation do what you'd expect them to.

Normal `tf.Tensor` objects are immutable. If we need to store things like weights that should be muttable, then we need to use `tf.variable`

In [12]:
var = tf.Variable([0,0,0])
# These are for weights above
var.assign([1, 2, 3])
var.assign_add([1, 1, 1])


<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

### Automatic Differentiation

Gradient Descent is an iterative optimization concept that can we used to find local minimum and maximum of the loss function

This is a process that happens after backprogation. Backpropagation is for calculating the gradients efficiently, while optimizers is for training the neural network, using the gradients computed with backpropagation. In short, all backpropagation does for us is compute the gradients.

To enable this, TensorFlow implements automatic differentiation (autodiff), which uses calculus to compute gradients.